#!/usr/bin/env node
// Packs game-icons.net SVGs (CC BY 3.0) into src/ui/iconset.ts as path data (currentColor fill).
//   node tools/build-icons.mjs
import fs from 'node:fs';
import path from 'node:path';
const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const SRC = path.join(ROOT, '.asset-scout/round2/icons');
const out = {};
for (const dir of fs.readdirSync(SRC)) {
  const d = path.join(SRC, dir);
  if (!fs.statSync(d).isDirectory()) continue;
  for (const f of fs.readdirSync(d)) {
    if (!f.endsWith('.svg')) continue;
    const svg = fs.readFileSync(path.join(d, f), 'utf8');
    const paths = [...svg.matchAll(/<path([^>]*)d="([^"]+)"/g)].map((m) => m[2]).filter((p) => p !== 'M0 0h512v512H0z');
    out[f.replace('.svg', '')] = paths.join(' ');
  }
}
const alias = {
  fire: 'fire_flame', water: 'water_drop', nature: 'leaf', earth: 'mountain', storm: 'lightning_bolt', wind: 'tornado', void: 'void_eye',
  sparkle: 'sparkles', wood: 'log_wood', crystal: 'crystal_cluster', gold: 'coin', aether: 'gem', ticket: 'scroll', essence: 'sparkles',
  dex: 'codex', bag: 'backpack', relic: 'crown', relics: 'crown', quests: 'quest_scroll', summon: 'crystal_ball', base: 'house_base', settings: 'gear_settings',
  profile: 'user_profile', achievements: 'trophy', build: 'hammer_build', logout: 'logout_door', sound: 'speaker', music: 'music_note', sprint: 'lightning_speed',
  strike: 'sword', heal: 'heart', guard: 'shield', boss: 'skull', camp: 'flag', waystone: 'waypoint_obelisk', daily: 'gift', incense: 'campfire', salt: 'gem', ether: 'potion',
};
const lines = Object.entries(out).sort().map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`);
const src = `// Generated by tools/build-icons.mjs from game-icons.net (CC BY 3.0: Lorc, Delapouite, Carl Olsen, sbed).\nexport const ICON_PATHS: Record<string, string> = {\n${lines.join('\n')}\n};\nexport const ICON_ALIAS: Record<string, string> = ${JSON.stringify(alias, null, 2)};\n`;
fs.writeFileSync(path.join(ROOT, 'src/ui/iconset.ts'), src);
console.log(`✓ ${Object.keys(out).length} icons → src/ui/iconset.ts (${(src.length / 1024).toFixed(0)} KB)`);
