// Roster build: reads tools/roster/batch-*.json (+ _legendary-prompts.json), merges them, and
// generates src/data/lines.ts (LINES) + src/data/forms.ts (NEW_FORMS) + docs/v3/creature-art.json.
// Run with: npx tsx tools/roster/build.ts
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = '/Users/tango/expedition-wilds';
const ROSTER_DIR = join(ROOT, 'tools/roster');

interface RosterForm {
  id: string; name: string; element: string;
  hp: number; atk: number; def: number; spd: number;
  height: number; model: string;
  learnset: [number, string][];
  rarity: string; catchRate: number;
  tint?: string; tintGlow?: string; rideable?: boolean; swim?: boolean;
  abilities: string[];
  lore: string;
}
interface RosterLine {
  id: string;
  branch?: { from: string; item: string } | null;
  stages: string[];
  existingCount: number;
  newForms: RosterForm[];
}
interface RosterPrompt { id: string; name: string; line: string; stage: number; element: string; prompt: string }
interface Batch { lines: RosterLine[]; prompts: RosterPrompt[] }

const batchFiles = readdirSync(ROSTER_DIR).filter((f) => /^batch-\d+\.json$/.test(f)).sort();
if (!batchFiles.length) throw new Error('No batch-*.json files found in tools/roster/');

const allLines: RosterLine[] = [];
const allPrompts: RosterPrompt[] = [];
for (const f of batchFiles) {
  const batch: Batch = JSON.parse(readFileSync(join(ROSTER_DIR, f), 'utf8'));
  allLines.push(...batch.lines);
  allPrompts.push(...batch.prompts);
  console.log(`${f}: ${batch.lines.length} lines, ${batch.lines.reduce((n, l) => n + l.newForms.length, 0)} new forms, ${batch.prompts.length} prompts`);
}
const legendaryPrompts: RosterPrompt[] = JSON.parse(readFileSync(join(ROSTER_DIR, '_legendary-prompts.json'), 'utf8'));
allPrompts.push(...legendaryPrompts);

console.log(`\nTOTAL: ${allLines.length} lines, ${allLines.reduce((n, l) => n + l.newForms.length, 0)} new forms, ${allPrompts.length} prompts (incl. ${legendaryPrompts.length} legendary)`);

// ── Serialisers ──────────────────────────────────────────────────────────
const q = (s: string) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const learnsetLit = (ls: [number, string][]) => `[${ls.map(([lvl, id]) => `[${lvl}, ${q(id)}]`).join(', ')}]`;
function extraLit(f: RosterForm): string {
  const parts: string[] = [];
  parts.push(`rarity: ${q(f.rarity)}`);
  parts.push(`catchRate: ${f.catchRate}`);
  if (f.tint) parts.push(`tint: ${q(f.tint)}`);
  if (f.tintGlow) parts.push(`tintGlow: ${q(f.tintGlow)}`);
  if (f.rideable) parts.push(`rideable: true`);
  if (f.swim) parts.push(`swim: true`);
  parts.push(`abilities: [${(f.abilities ?? []).map(q).join(', ')}]`);
  return `{ ${parts.join(', ')} }`;
}
function rowLit(f: RosterForm): string {
  return `[${q(f.id)}, ${q(f.name)}, ${q(f.element)}, ${f.hp}, ${f.atk}, ${f.def}, ${f.spd}, ${f.height}, ${q(f.model)}, ${learnsetLit(f.learnset)}, ${extraLit(f)}]`;
}
function lineLit(l: RosterLine): string {
  const stages = `[${l.stages.map(q).join(', ')}] as [string, string, string, string, string]`;
  const branch = l.branch ? `, branch: { from: ${q(l.branch.from)}, item: ${q(l.branch.item)} as ItemId }` : '';
  return `  { id: ${q(l.id)}, stages: ${stages}${branch} },`;
}

// ── src/data/lines.ts ────────────────────────────────────────────────────
const linesHeader = `// Evolution lines (v3): every non-legendary Mystic belongs to a five-form line that evolves at
// levels 10 → 20 → 30 → 35 (Miscrits-style: evolution happens when training reaches the level).
// Stone forms are branch lines that share the first form: evolve with the stone from Lv 10.
// Generated by the roster pass (tools/roster); see species.ts → applyLines().
import type { ItemId } from './items';

export const EVO_LEVELS = [10, 20, 30, 35] as const;

export interface LineDef {
  /** Line id = the first form's species id (branch lines: \`<first>__<stone form>\`). */
  id: string;
  stages: [string, string, string, string, string];
  /** Branch line: evolves from \`from\` (stage 1) with \`item\` instead of by level. */
  branch?: { from: string; item: ItemId };
}

export const LINES: LineDef[] = [
${allLines.map(lineLit).join('\n')}
];
`;
writeFileSync(join(ROOT, 'src/data/lines.ts'), linesHeader);

// ── src/data/forms.ts ────────────────────────────────────────────────────
const formsHeader = `// New evolution forms added by the v3 roster pass (tools/roster). Same row format as species.ts.
import type { Row } from './species';

export const NEW_FORMS: [Row, string][] = [
${allLines.map((l) => l.newForms.map((f) => `  [${rowLit(f)}, ${q(f.lore)}],`).join('\n')).join('\n')}
];
`;
writeFileSync(join(ROOT, 'src/data/forms.ts'), formsHeader);

// ── docs/v3/creature-art.json ───────────────────────────────────────────
writeFileSync(join(ROOT, 'docs/v3/creature-art.json'), JSON.stringify(allPrompts, null, 2) + '\n');

console.log('\nWrote src/data/lines.ts, src/data/forms.ts, docs/v3/creature-art.json');
