// Evolution lines (v3): every non-legendary Mystic belongs to a five-form line that evolves at
// levels 10 → 20 → 30 → 35 (Miscrits-style: evolution happens when training reaches the level).
// Stone forms are branch lines that share the first form: evolve with the stone from Lv 10.
// Generated by the roster pass (tools/roster); see species.ts → applyLines().
import type { ItemId } from './items';

export const EVO_LEVELS = [10, 20, 30, 35] as const;

export interface LineDef {
  /** Line id = the first form's species id (branch lines: `<first>__<stone form>`). */
  id: string;
  stages: [string, string, string, string, string];
  /** Branch line: evolves from `from` (stage 1) with `item` instead of by level. */
  branch?: { from: string; item: ItemId };
}

export const LINES: LineDef[] = [];
